version: "3.3"

services:

  flask:
    build: .
    container_name: app
    restart: always
    expose:
      - 5000
    networks: 
      - appnet

  db:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks: 
      - appnet
networks: 
  appnet:
    